/*
 * CallVault: FOSS call recording, self-contained over embedded ADB
 *  Copyright (C) 2026-present The CallVault Authors
 *  This software is licensed under the GNU General Public License v3 or later, with additional terms as permitted under Section 7.
 *  The full license text is available in the LICENSE file at the root of this project.
 *  This software is distributed WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 */

package com.baba.callvault.summary

/**
 * JNI bridge to llama.cpp.
 *
 * The same contract as [com.baba.callvault.transcription.WhisperNative], for the same reasons: one
 * model may not be driven from two threads at once, so nothing calls these directly — [SummaryEngine]
 * owns that serialisation and is the only supported entry point. The raw `Long` is a model pointer
 * and must be paired with exactly one [freeContext].
 *
 * Runs in the app process, never in the privileged recorder daemon. Summarising needs no privilege,
 * and putting a CPU-saturating job in the capture process would risk the one thing that must not
 * fail.
 *
 * [libDir] on the two entry points below is `context.applicationInfo.nativeLibraryDir` — the same
 * contract, for the same reason, as [com.baba.callvault.transcription.WhisperNative].
 */
object LlamaNative {
    init { System.loadLibrary("llamacv") }

    /**
     * ggml build/CPU feature string. Used to confirm the native library loaded at all.
     *
     * Built entirely from the backend registry, so it is blank rather than wrong when the CPU
     * backend was not found — and it names the ARM features the chosen variant was compiled with.
     */
    external fun systemInfo(libDir: String): String

    /** @return an opaque model pointer, or 0 when the model could not be loaded. */
    external fun initContext(modelPath: String, libDir: String): Long

    /** Releases a model from [initContext]. Safe to call with 0. */
    external fun freeContext(ptr: Long)

    /**
     * How many tokens [text] costs for this model, or negative when it cannot be tokenised.
     *
     * Chunking guesses in characters because it has no model to hand; this is how that guess gets
     * checked against the truth, which differs sharply by script — Hebrew and Arabic carry far more
     * tokens per character than English.
     */
    external fun countTokens(ptr: Long, text: String): Int

    /**
     * Completes [prompt], greedily, stopping at end-of-generation, [maxTokens], or [requestAbort].
     *
     * Greedy rather than sampled: a summary is not creative writing, and determinism is what lets one
     * model's output be compared with another's.
     *
     * @param grammar GBNF constraining the output, or null to generate freely. Given one, output
     *   that would break the grammar is not merely discouraged — the tokens are never candidates.
     */
    external fun generate(
        ptr: Long,
        prompt: String,
        maxTokens: Int,
        threads: Int,
        grammar: String?
    ): String

    /**
     * Asks a run in progress to stop, from any thread.
     *
     * Reaches the prefill as well as the token loop. On a long transcript the prefill *is* the wait,
     * so an abort that only checked between tokens would look broken for a minute. The flag is
     * cleared at the start of every [generate], so a stale abort cannot kill the following run.
     */
    external fun requestAbort()

    /**
     * Whether llama will actually apply [grammar], asked before it matters.
     *
     * [generate] falls back to **unconstrained** output when a grammar fails to parse. That fallback
     * is right — a summary that needs repairing beats no summary — but it was invisible: a native log
     * line to logcat, which rotates within minutes and is off by default, while the app produced
     * plausible-looking output with no constraint behind it at all.
     *
     * The grammar is generated by our own code and never by a user, so a parse failure is a
     * programming error that could ship unnoticed. Asking here puts the answer in the app's own log,
     * where a bug report can find it.
     *
     * @return false when the grammar would be ignored, or when [ptr] is not a loaded model.
     */
    external fun grammarAccepted(ptr: Long, grammar: String): Boolean
}
